import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid
get_ipython().run_line_magic('matplotlib', 'widget')
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')

import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

from public_tests import * 

from autils import *
from lab_utils_softmax import plt_softmax
np.set_printoptions(precision=2)


# <a name="2"></a>
# ## 2 - ReLU Activation
# This week, a new activation was introduced, the Rectified Linear Unit (ReLU). 
# $$ a = max(0,z) \quad\quad\text {# ReLU function} $$

# In[79]:


plt_act_trio()


# <img align="right" src="./images/C2_W2_ReLu.png"     style=" width:380px; padding: 10px 20px; " >
# The example from the lecture on the right shows an application of the ReLU. In this example, the derived "awareness" feature is not binary but has a continuous range of values. The sigmoid is best for on/off or binary situations. The ReLU provides a continuous linear relationship. Additionally it has an 'off' range where the output is zero.     
# The "off" feature makes the ReLU a Non-Linear activation. Why is this needed? This enables multiple units to contribute to to the resulting function without interfering. This is examined more in the supporting optional lab. 

# <a name="3"></a>
# ## 3 - Softmax Function
# A multiclass neural network generates N outputs. One output is selected as the predicted answer. In the output layer, a vector $\mathbf{z}$ is generated by a linear function which is fed into a softmax function. The softmax function converts $\mathbf{z}$  into a probability distribution as described below. After applying softmax, each output will be between 0 and 1 and the outputs will sum to 1. They can be interpreted as probabilities. The larger inputs to the softmax will correspond to larger output probabilities.
# <center>  <img  src="./images/C2_W2_NNSoftmax.PNG" width="600" />  

# The softmax function can be written:
# $$a_j = \frac{e^{z_j}}{ \sum_{k=0}^{N-1}{e^{z_k} }} \tag{1}$$
# 
# Where $z = \mathbf{w} \cdot \mathbf{x} + b$ and N is the number of feature/categories in the output layer.  

# <a name="ex01"></a>
# ### Exercise 1
# Let's create a NumPy implementation:

# In[80]:


# UNQ_C1
# GRADED CELL: my_softmax

def my_softmax(z):  
    """ Softmax converts a vector of values to a probability distribution.
    Args:
      z (ndarray (N,))  : input data, N features
    Returns:
      a (ndarray (N,))  : softmax of z
    """    
    ### START CODE HERE ### 
    
    ez = np.exp(z)
    a = ez/np.sum(ez)
    
    
        
    
        
    
    
    ### END CODE HERE ### 
    return a


# In[81]:


z = np.array([1., 2., 3., 4.])
a = my_softmax(z)
atf = tf.nn.softmax(z)
print(f"my_softmax(z):         {a}")
print(f"tensorflow softmax(z): {atf}")

# BEGIN UNIT TEST  
test_my_softmax(my_softmax)
# END UNIT TEST  


# <details>
#   <summary><font size="3" color="darkgreen"><b>Click for hints</b></font></summary>
#     One implementation uses for loop to first build the denominator and then a second loop to calculate each output.
#     
# ```python
# def my_softmax(z):  
#     N = len(z)
#     a =                     # initialize a to zeros 
#     ez_sum =                # initialize sum to zero
#     for k in range(N):      # loop over number of outputs             
#         ez_sum +=           # sum exp(z[k]) to build the shared denominator      
#     for j in range(N):      # loop over number of outputs again                
#         a[j] =              # divide each the exp of each output by the denominator   
#     return(a)
# ```
# <details>
#   <summary><font size="3" color="darkgreen"><b>Click for code</b></font></summary>
#    
# ```python
# def my_softmax(z):  
#     N = len(z)
#     a = np.zeros(N)
#     ez_sum = 0
#     for k in range(N):                
#         ez_sum += np.exp(z[k])       
#     for j in range(N):                
#         a[j] = np.exp(z[j])/ez_sum   
#     return(a)
# 
# Or, a vector implementation:
# 
# def my_softmax(z):  
#     ez = np.exp(z)              
#     a = ez/np.sum(ez)           
#     return(a)
# 
# ```
# 

# Below, vary the values of the `z` inputs. Note in particular how the exponential in the numerator magnifies small differences in the values. Note as well that the output values sum to one.

# In[82]:


plt.close("all")
plt_softmax(my_softmax)


# <a name="4"></a>
# ## 4 - Neural Networks
# 
# In last weeks assignment, you implemented a neural network to do binary classification. This week you will extend that to multiclass classification. This will utilize the softmax activation.
# 
# 
# <a name="4.1"></a>
# ### 4.1 Problem Statement
# 
# In this exercise, you will use a neural network to recognize ten handwritten digits, 0-9. This is a multiclass classification task where one of n choices is selected. Automated handwritten digit recognition is widely used today - from recognizing zip codes (postal codes) on mail envelopes to recognizing amounts written on bank checks. 
# 
# 
# <a name="4.2"></a>
# ### 4.2 Dataset
# 
# You will start by loading the dataset for this task. 
# - The `load_data()` function shown below loads the data into variables `X` and `y`
# 
# 
# - The data set contains 5000 training examples of handwritten digits $^1$.  
# 
#     - Each training example is a 20-pixel x 20-pixel grayscale image of the digit. 
#         - Each pixel is represented by a floating-point number indicating the grayscale intensity at that location. 
#         - The 20 by 20 grid of pixels is “unrolled” into a 400-dimensional vector. 
#         - Each training examples becomes a single row in our data matrix `X`. 
#         - This gives us a 5000 x 400 matrix `X` where every row is a training example of a handwritten digit image.
# 
# $$X = 
# \left(\begin{array}{cc} 
# --- (x^{(1)}) --- \\
# --- (x^{(2)}) --- \\
# \vdots \\ 
# --- (x^{(m)}) --- 
# \end{array}\right)$$ 
# 
# - The second part of the training set is a 5000 x 1 dimensional vector `y` that contains labels for the training set
#     - `y = 0` if the image is of the digit `0`, `y = 4` if the image is of the digit `4` and so on.
# 
# $^1$<sub> This is a subset of the MNIST handwritten digit dataset (http://yann.lecun.com/exdb/mnist/)</sub>

# In[83]:


# load dataset
X, y = load_data()


# #### 4.2.1 View the variables
# Let's get more familiar with your dataset.  
# - A good place to start is to print out each variable and see what it contains.
# 
# The code below prints the first element in the variables `X` and `y`.  

# In[84]:


print ('The first element of X is: ', X[0])


# In[85]:


print ('The first element of y is: ', y[0,0])
print ('The last element of y is: ', y[-1,0])


# #### 4.2.2 Check the dimensions of your variables
# 
# Another way to get familiar with your data is to view its dimensions. Please print the shape of `X` and `y` and see how many training examples you have in your dataset.

# In[86]:


print ('The shape of X is: ' + str(X.shape))
print ('The shape of y is: ' + str(y.shape))

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
# You do not need to modify anything in this cell

m, n = X.shape

fig, axes = plt.subplots(8,8, figsize=(5,5))
fig.tight_layout(pad=0.13,rect=[0, 0.03, 1, 0.91]) #[left, bottom, right, top]

#fig.tight_layout(pad=0.5)
widgvis(fig)
for i,ax in enumerate(axes.flat):
    # Select random indices
    random_index = np.random.randint(m)
    
    # Select rows corresponding to the random indices and
    # reshape the image
    X_random_reshaped = X[random_index].reshape((20,20)).T
    
    # Display the image
    ax.imshow(X_random_reshaped, cmap='gray')
    
    # Display the label above the image
    ax.set_title(y[random_index,0])
    ax.set_axis_off()
    fig.suptitle("Label, image", fontsize=14)
    
    
# UNQ_C2
# GRADED CELL: Sequential model
tf.random.set_seed(1234) # for consistent results
model = Sequential(
    [               
        ### START CODE HERE ### 
        
        Dense(25, activation = 'relu',   name = "L1"),
        Dense(15, activation = 'relu', name = "L2"),
        Dense(10, activation = 'linear', name = "L3")
        
        ### END CODE HERE ### 
    ], name = "my_model" 
)


# In[89]:


model.summary()


# <details>
#   <summary><font size="3" color="darkgreen"><b>Expected Output (Click to expand)</b></font></summary>
# The `model.summary()` function displays a useful summary of the model. Note, the names of the layers may vary as they are auto-generated unless the name is specified.    
#     
# ```
# Model: "my_model"
# _________________________________________________________________
# Layer (type)                 Output Shape              Param #   
# =================================================================
# L1 (Dense)                   (None, 25)                10025     
# _________________________________________________________________
# L2 (Dense)                   (None, 15)                390       
# _________________________________________________________________
# L3 (Dense)                   (None, 10)                160       
# =================================================================
# Total params: 10,575
# Trainable params: 10,575
# Non-trainable params: 0
# _________________________________________________________________
# ```

# <details>
#   <summary><font size="3" color="darkgreen"><b>Click for hints</b></font></summary>
#     
# ```python
# tf.random.set_seed(1234)
# model = Sequential(
#     [               
#         ### START CODE HERE ### 
#         tf.keras.Input(shape=(400,)),     # @REPLACE 
#         Dense(25, activation='relu', name = "L1"), # @REPLACE 
#         Dense(15, activation='relu',  name = "L2"), # @REPLACE  
#         Dense(10, activation='linear', name = "L3"),  # @REPLACE 
#         ### END CODE HERE ### 
#     ], name = "my_model" 
# )
# ``` 

# In[ ]:


# BEGIN UNIT TEST     
test_model(model, 10, 400)
# END UNIT TEST     


# The parameter counts shown in the summary correspond to the number of elements in the weight and bias arrays as shown below.

# Let's further examine the weights to verify that tensorflow produced the same dimensions as we calculated above.

# In[ ]:


[layer1, layer2, layer3] = model.layers


# In[ ]:


#### Examine Weights shapes
W1,b1 = layer1.get_weights()
W2,b2 = layer2.get_weights()
W3,b3 = layer3.get_weights()
print(f"W1 shape = {W1.shape}, b1 shape = {b1.shape}")
print(f"W2 shape = {W2.shape}, b2 shape = {b2.shape}")
print(f"W3 shape = {W3.shape}, b3 shape = {b3.shape}")


# **Expected Output**
# ```
# W1 shape = (400, 25), b1 shape = (25,)  
# W2 shape = (25, 15), b2 shape = (15,)  
# W3 shape = (15, 10), b3 shape = (10,)
# ```

# The following code:
# * defines a loss function, `SparseCategoricalCrossentropy` and indicates the softmax should be included with the  loss calculation by adding `from_logits=True`)
# * defines an optimizer. A popular choice is Adaptive Moment (Adam) which was described in lecture.

# In[ ]:


model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
)

history = model.fit(
    X,y,
    epochs=40
)


# #### Epochs and batches
# In the `compile` statement above, the number of `epochs` was set to 100. This specifies that the entire data set should be applied during training 100 times.  During training, you see output describing the progress of training that looks like this:
# ```
# Epoch 1/100
# 157/157 [==============================] - 0s 1ms/step - loss: 2.2770
# ```
# The first line, `Epoch 1/100`, describes which epoch the model is currently running. For efficiency, the training data set is broken into 'batches'. The default size of a batch in Tensorflow is 32. There are 5000 examples in our data set or roughly 157 batches. The notation on the 2nd line `157/157 [====` is describing which batch has been executed.

# #### Loss  (cost)
# In course 1, we learned to track the progress of gradient descent by monitoring the cost. Ideally, the cost will decrease as the number of iterations of the algorithm increases. Tensorflow refers to the cost as `loss`. Above, you saw the loss displayed each epoch as `model.fit` was executing. The [.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model) method returns a variety of metrics including the loss. This is captured in the `history` variable above. This can be used to examine the loss in a plot as shown below.

# In[ ]:


plot_loss_tf(history)


# #### Prediction 
# To make a prediction, use Keras `predict`. Below, X[1015] contains an image of a two.

# In[ ]:


image_of_two = X[1015]
display_digit(image_of_two)

prediction = model.predict(image_of_two.reshape(1,400))  # prediction

print(f" predicting a Two: \n{prediction}")
print(f" Largest Prediction index: {np.argmax(prediction)}")


# The largest output is prediction[2], indicating the predicted digit is a '2'. If the problem only requires a selection, that is sufficient. Use NumPy [argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) to select it. If the problem requires a probability, a softmax is required:

# In[ ]:


prediction_p = tf.nn.softmax(prediction)

print(f" predicting a Two. Probability vector: \n{prediction_p}")
print(f"Total of predictions: {np.sum(prediction_p):0.3f}")


# To return an integer representing the predicted target, you want the index of the largest probability. This is accomplished with the Numpy [argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) function.

# In[ ]:


yhat = np.argmax(prediction_p)

print(f"np.argmax(prediction_p): {yhat}")


# Let's compare the predictions vs the labels for a random sample of 64 digits. This takes a moment to run.

# In[ ]:


import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
# You do not need to modify anything in this cell

m, n = X.shape

fig, axes = plt.subplots(8,8, figsize=(5,5))
fig.tight_layout(pad=0.13,rect=[0, 0.03, 1, 0.91]) #[left, bottom, right, top]
widgvis(fig)
for i,ax in enumerate(axes.flat):
    # Select random indices
    random_index = np.random.randint(m)
    
    # Select rows corresponding to the random indices and
    # reshape the image
    X_random_reshaped = X[random_index].reshape((20,20)).T
    
    # Display the image
    ax.imshow(X_random_reshaped, cmap='gray')
    
    # Predict using the Neural Network
    prediction = model.predict(X[random_index].reshape(1,400))
    prediction_p = tf.nn.softmax(prediction)
    yhat = np.argmax(prediction_p)
    
    # Display the label above the image
    ax.set_title(f"{y[random_index,0]},{yhat}",fontsize=10)
    ax.set_axis_off()
fig.suptitle("Label, yhat", fontsize=14)
plt.show()


# Let's look at some of the errors. 
# >Note: increasing the number of training epochs can eliminate the errors on this data set.

# In[ ]:


print( f"{display_errors(model,X,y)} errors out of {len(X)} images")
